[package]
name = "pub-automod"
version = "0.1.0"
authors = ["David Tolnay <dtolnay@gmail.com>", "Ari Lotter <arilotter@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Pull in every source file in a directory as a module."
repository = "https://github.com/arilotter/automod"
readme = "README.md"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
